### PR TITLE
Update IBM console and CSV version to 0.2.1

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

### CODE REVIEW

**Review by bipuladh — COMMENTED** [review]
Maybe we should also move to quay at this point?

**Comment by iamniting** [comment]
> Maybe we should also move to quay at this point?

That is on the IBM folks, we can bring this again in one of our meetings. But I don't want this PR to wait on it.

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
