### PR TITLE
Bug 2296533:[release-4.14] api: update ocs-operator pkg version

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Update ocs-operator pkg version to include new api changes
Ref BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2276694

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
> Can you move the new require block in the existing require block?
> 
> Can we reduce these other packages update?

I have moved the require modules to one section, but other package updates can't be controlled they come automatically due to ocs-operator upgrade as dependencies.

**Review by iamniting — APPROVED** [review]

**Review by iamniting — CHANGES_REQUESTED** [review]
Is it possible to reduce these changes and only updates OCS?

**Comment by Nikhil-Ladha** [comment]
> Is it possible to reduce these changes and only updates OCS?

Only ocs-operator is updated, rest of the changes are brought along by ocs-op itself.

**Review by iamniting — APPROVED** [review]

**Pull request merged**
