### PR TITLE
bundle: start creating file based catalog instead of sqlite

### PR DESCRIPTION
**Pull request by iamniting**
Sqlite-based catalogs and their related subcommands are deprecated.
Support for them will be removed in a future release.

Ref:
https://olm.operatorframework.io/docs/reference/file-based-catalogs/
https://olm.operatorframework.io/docs/reference/veneers/

Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

### CODE REVIEW

**Comment by iamniting** [comment]
The workflow is failing as code for accessing the secret is added into the same PR I guess.

**Review by jarrpa — COMMENTED** [review]
Changes look good. Any reason to keep `index.Dockerfile` after this if all the checks are passing? You should also probably update (or just remove) the "comma-separated list" comment in the `.mk` file.

**Comment by iamniting** [comment]
> Changes look good. Any reason to keep `index.Dockerfile` after this if all the checks are passing? You should also probably update (or just remove) the "comma-separated list" comment in the `.mk` file.

done, I missed it earlier

**Review by malayparida2000 — APPROVED** [review]
/lgtm

**Pull request merged**
