### PR TITLE
config: Add resources to enable Prometheus Monitoring

### PR DESCRIPTION
**Pull request by anmolsachan**
Signed-off-by: Anmol Sachan <anmol13694@gmail.com>

Tested in the openshift-storage namespace.
Screenshot from 2021-08-11 19-57-20

### CODE REVIEW

**Comment by anmolsachan** [comment]
@umangachapagain @jarrpa Please review.

**Review by iamniting — CHANGES_REQUESTED** [review]
@anmolsachan the content looks good to me. Can you pls separate these changes into 2 commits first one for the code you edited and the second one for the generated code also please change the type of commit refer https://github.com/red-hat-storage/odf-operator/blob/main/CONTRIBUTING.md

**Comment by anmolsachan** [comment]
> @anmolsachan the content looks good to me. Can you pls separate these changes into 2 commits first one for the code you edited and the second one for the generated code also please change the type of commit refer https://github.com/red-hat-storage/odf-operator/blob/main/CONTRIBUTING.md

Ack, Thanks for the review. I will update.

**Comment by anmolsachan** [comment]
@iamniting Please review. I have updated the PR as requested.

**Comment by iamniting** [comment]
@anmolsachan It looks like there is a problem with some YAML files. Can you pls look at them and push changes if `make bundle` works locally.

**Comment by anmolsachan** [comment]
@iamniting I found the issue finally. Was just a simple string. Somehow wasn't visible to me. Thank you for it. Please review

**Comment by iamniting** [comment]
@anmolsachan thanks for fixing it, I see one more problem in the first commit. also, I would like to see **Output of `make bundle`.** in the body of your second commit-msg.
Screenshot from 2021-08-20 16-38-17

**Comment by anmolsachan** [comment]
> @anmolsachan thanks for fixing it, I see one more problem in the first commit. also, I would like to see **Output of `make bundle`.** in the body of your second commit-msg.

@iamniting I added the output of make bundle in the second commti, but it's too long. Please let me know if you need me to remove it.

**Comment by iamniting** [comment]
> > @anmolsachan thanks for fixing it, I see one more problem in the first commit. also, I would like to see **Output of `make bundle`.** in the body of your second commit-msg.
> 
> @iamniting I added the output of make bundle in the second commti, but it's too long. Please let me know if you need me to remove it.

@anmolsachan I mean something like this, not the whole output.
Screenshot from 2021-08-23 11-07-01

**Comment by anmolsachan** [comment]
@iamniting Fixed it. Please review.

**Review by iamniting — APPROVED** [review]
/lgtm

**Pull request merged**
