### PR TITLE
add odf as a keyword in quickstart

### PR DESCRIPTION
**Pull request by weirdwiz**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2035876

### CODE REVIEW

**Comment by iamniting** [comment]
@weirdwiz Can you change the commit-msg? following this guide https://github.com/red-hat-storage/odf-operator/blob/main/CONTRIBUTING.md#commit-structure

Will this show up while searching odf in a small case or camel case?

**Comment by weirdwiz** [comment]
> Will this show up while searching odf in a small case or camel case?

Yes, this will show up when searching in small case or camel case.

**Comment by iamniting** [comment]
@weirdwiz We should not add the bug in the title of a PR which is raised in the main branch

**Comment by weirdwiz** [comment]
Noted, thanks for pointing out.

**Review by iamniting — APPROVED** [review]
/lgtm

**Pull request merged**
