### PR TITLE
Bug 2296521: [release-4.16] api: update ocs-operator pkg version

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Update ocs-operator pkg version to include new api changes
Ref BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2276694

### CODE REVIEW

**Review by iamniting — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
@iamniting I guess we can merge this (and other backports) PR without a bz, right?

**Comment by iamniting** [comment]
> @iamniting I guess we can merge this (and other backports) PR without a bz, right?

no we need BZ

**Comment by iamniting** [comment]
> @iamniting we are using `gingko@latest` in `make-tools` i.e, causing to download the latest gingko version which requires golang 1.22. I think we should pin to a version similar to one we use in go.mod. WDYT? Ref: https://github.com/red-hat-storage/odf-operator/blob/release-4.16/hack/make-tools.mk#L17

Yes, we should do that, Can you pls create the required PRs in all branches I will merge them without the bugs.

**Comment by Nikhil-Ladha** [comment]
Here's the PR: #484

**Pull request merged**
