### PR TITLE
controller: reuse the context from reconcile

### PR DESCRIPTION
**Pull request by Madhu-1**
We dont need to create a new context for each time for a reconcile we should use the ctx from the Reconcile for all the dependent operations.

### CODE REVIEW

**Comment by Madhu-1** [comment]
@iamniting where i can find details about the test failure?

**Review by iamniting — CHANGES_REQUESTED** [review]
Can we save the context to the recociler func and use it from there. I will save us from passing ctx here and there if the func is on top of reconciler struct.

**Comment by Madhu-1** [comment]
> Can we save the context to the recociler func and use it from there. I will save us from passing ctx here and there if the func is on top of reconciler struct.

sorry didn't get the suggestion, Do you mean saving as a global variable? if yes, i would not do it as its against the practice. main goal is that we should not create context when reconciling instead we should use the context created for the `Reconcile`

**Comment by Madhu-1** [comment]
> Can we save the context to the recociler func and use it from there. I will save us from passing ctx here and there if the func is on top of reconciler struct.

got it now, let me take that in to consideration and do it

**Pull request closed without merging**
