### PR TITLE
controllers: remove StorageClass encryption page from ODF QuickStart guide

### PR DESCRIPTION
**Pull request by SanjalKatiyar**
This PR is to revert the changes introduced by https://github.com/red-hat-storage/odf-operator/pull/151
#151 is out of 4.10 now.

Signed-off-by: sanjalkatiyar <sanjaldhir@gmail.com>

### CODE REVIEW

**Comment by iamniting** [comment]
@SanjalKatiyar Can you use the `git revert` command for this and use autogenerated commit-msg.

**Comment by SanjalKatiyar** [comment]
> @SanjalKatiyar Can you use the `git revert` command for this and use autogenerated commit-msg.

used `git revert` and updated the PR.
/assign @iamniting

**Review by iamniting — APPROVED** [review]
/lgtm

**Pull request merged**
