### PR TITLE
bundle: fix ibm-console container args

### PR DESCRIPTION
**Pull request by shdn-ibm**
Signed-of-by: Ning Ding <shdn@cn.ibm.com>

### CODE REVIEW

**Comment by shdn-ibm** [comment]
hi, @iamniting I have no idea about the DCO failure. Any suggestion?

**Comment by iamniting** [comment]
> hi, @iamniting I have no idea about the DCO failure. Any suggestion?

Can you paste the output of the git log of your commit?

**Comment by shdn-ibm** [comment]
`commit 30d221eea77bad6dfad0375de715ff1459af762a (HEAD -> fix/ibm-console, origin/fix/ibm-console)
Author: Ning Ding <shdn@cn.ibm.com>
Date:   Wed Sep 15 14:11:56 2021 +0800

    bundle: fix ibm-console container args
    
    Signed-of-by: Ning Ding <shdn@cn.ibm.com>`

**Comment by iamniting** [comment]
> commit [30d221e](https://github.com/red-hat-storage/odf-operator/commit/30d221eea77bad6dfad0375de715ff1459af762a) (HEAD -> fix/ibm-console, origin/fix/ibm-console)
> Author: Ning Ding [shdn@cn.ibm.com](mailto:shdn@cn.ibm.com)
> Date: Wed Sep 15 14:11:56 2021 +0800
> 
> ```
> bundle: fix ibm-console container args
> 
> Signed-of-by: Ning Ding <shdn@cn.ibm.com>
> ```

This looks good to me, even I am not sure what's wrong with it. BTW I think we no longer required this as we moved this out.

**Comment by shdn-ibm** [comment]
I have seen the new pull request in https://github.com/IBM/ibm-storage-odf-operator/pull/33
So when will you move the code? because if https://github.com/IBM/ibm-storage-odf-operator/pull/33 get merged, there will be two ibm-console containers installed.

**Comment by iamniting** [comment]
> I have seen the new pull request in [IBM/ibm-storage-odf-operator#33](https://github.com/IBM/ibm-storage-odf-operator/pull/33)
> So when will you move the code? because if [IBM/ibm-storage-odf-operator#33](https://github.com/IBM/ibm-storage-odf-operator/pull/33) get merged, there will be two ibm-console containers installed.

We will try to get it done by today.

**Comment by shdn-ibm** [comment]
okay.
close this pr due to code removed

**Pull request closed without merging**
