### PR TITLE
update child operator versions

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

### CODE REVIEW

**Review by malayparida2000 — APPROVED** [review]
/lgtm

**Comment by malayparida2000** [comment]
@iamniting What will we do for csi-addons & noobaa?

**Comment by iamniting** [comment]
> @iamniting What will we do for csi-addons & noobaa?

csi-addons there is already a version available, but we can not make use of it until `ocs-client-operator` uses the new one.

noobaa we need to check again with the noobaa team.

**Review by malayparida2000 — APPROVED** [review]
/lgtm

**Pull request merged**
