### PR TITLE
bundle: update operator card description

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=2024424

### CODE REVIEW

**Review by agarwal-mudit — APPROVED** [review]
/lgtm

**Comment by iamniting** [comment]
Waiting for @jarrpa to take a look before it is merged.

**Review by jarrpa — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
