### PR TITLE
bundle: add readOnlyRootFilesystem for odf-operator

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2273386

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
LGTM.

But, I remember when we simply added `readOnlyRootFilesystem: true` for `odf-console` pod, we had to revert the changes temporarily, so better to test this once (if not already) on close to prod-like environment (rhceph-dev) and verify if all pods (manager/proxy/console etc) are running as expected.

**Comment by iamniting** [comment]
> LGTM.
> 
> But, I remember when we simply added `readOnlyRootFilesystem: true` for `odf-console` pod, we had to revert the changes temporarily (had to do much more changes to make it work), so better to test this once (if not already) on close to prod-like environment (rhceph-dev) and verify if all pods (manager/proxy/console etc) are running as expected.

Tested, It is working well.

**Review by Nikhil-Ladha — APPROVED** [review]
lgtm

**Pull request merged**
