### PR TITLE
console: update compatibility support matrix for 4.13

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
ODF 4.13 supports OCP 4.13 and 4.14.
Signed-off-by: Timothy Asir <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@SanjalKatiyar Please review

**Comment by SanjalKatiyar** [comment]
/lgtm
cc @bipuladh @iamniting

**Review by iamniting — APPROVED** [review]

**Pull request merged**
